// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DailyContentItems daily content items
// swagger:model dailyContentItems
type DailyContentItems struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this daily content items
func (m *DailyContentItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DailyContentItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DailyContentItems) UnmarshalBinary(b []byte) error {
	var res DailyContentItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
