// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserSummary 用于列表页等用户信息显示
// swagger:model user_summary
type UserSummary struct {

	// 用户唯一id
	// Required: true
	ID *int64 `json:"id"`

	// 用户显示名称
	// Required: true
	Name *string `json:"name"`

	// 用户显示小头像
	// Required: true
	SmallImage *string `json:"small_image"`
}

// Validate validates this user summary
func (m *UserSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSmallImage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserSummary) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *UserSummary) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *UserSummary) validateSmallImage(formats strfmt.Registry) error {

	if err := validate.Required("small_image", "body", m.SmallImage); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserSummary) UnmarshalBinary(b []byte) error {
	var res UserSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
